apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (print .Values.service "-yarp-config") | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- if .Values.yarpConfig.RoutesSettingFile }}
  "RoutesSetting.json": |-
{{ .Files.Get .Values.yarpConfig.RoutesSettingFile | indent 4 }}
  {{- end }}
  {{- if .Values.yarpConfig.ClustersSettingFile }}
  "ClustersSetting.json": |-
{{ .Files.Get .Values.yarpConfig.ClustersSettingFile | indent 4 }}
  {{- end }}
